### ISSUE TITLE
printing a BDD in human readable format

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#1]
check out if this function **BddEnc_print_set_of_states** or similar are useful.

starting point is the file
SWP2016/NuSMV-2.6.0/NuSMV/code/nusmv/core/fsm/bdd/BddFsmPrint.c

**Comment by rickyheinitz** [comment]
ich hab mal ein bisschen mit den print-Funktionen in `BddEnc.c` gespielt und sie überredet, keinen Speicherzugriffsfehler mehr zu werfen.
Die Ausgabe von `BddEnc_print_bdd` und `BddEnc_print_set_of_states` ist jetzt in `Mc_CheckCTLSpec()` mit drin. 
Ich bin mir aber gar nicht sicher, ob die Ausgabe so sinnvoll ist und damit irgendwas weiter anzufangen ist, oder ob doch die Version mit der Formel die bessere Variante ist? Hab leider auch noch nicht rausgefunden, wie ich die Variablen-Namen als String bekomme.
