### ISSUE TITLE
Organisation der Funktionen

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#10]
Hi,

soweit ich sehen kann gibt es zwei Dateien an denen wir arbeiten:
- [fsm/bdd/BddFsmPrint.c](../../SWP2016/blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/fsm/bdd/BddFsmPrint.c) und 
- [mc/mcMc.c](../../SWP2016/blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/mc/mcMc.c)

und derzeit drei Funktionen:
- `BddFsm_print_interesting_states_info`
- `try_to_print_this`
- `print_this`

Ich würde vorschlagen die drei Funktionen in eine, z.B. `BddFsm_print_accepting_states_info` zusammenzufassen. Damit bleibt [mc/mcMc.c](../../SWP2016/blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/mc/mcMc.c) möglichst sauber und die Ausgabe der accepting states entspricht der von z.B. den fair states.

**Comment by rickyheinitz** [comment]
Ich habe jetzt mal versucht, all unsere Funktionen als Package zusammenzufassen. Falls ich nicht den Überblick verloren habe, wären das:
- `dd_dump_factored_form` in `dd.c`
- `try_to_print_this`, `print_states`, `print_spec_only` in `mcMc.c`
- `BddFsm_print_interesting_states_info` in `BddFsmPrint.c`

Zur  `dd_dump_factored_form` kommt dann noch die Anpassung von den Cudd-Funktionen dazu, also `ddDoDumpFactoredForm` und `DumpFactoredForm`.
Leider funktioniert das nicht so leicht, wie ich mir das gedacht habe mit dem Package. Ich verstehe die Struktur der `makefiles` auf den unterschiedlichen Ebenen noch nicht. Deshalb habe ich jetzt erstmal angefangen, die Funktionen in eigene Dateien auszulagern, aber in den jeweiligen Ordnern zu lassen - also die `Dump`-Varianten in `dd` und so weiter. Ich kann gerne auch noch schauen, wie das mit einem eigenen Ordner für all unseren Kram wäre, aber erstmal dachte ich, ich mach das so, damit wir weiter testen können.

**Comment by rickyheinitz** [comment]
Ich hatte gestern abend vergessen, die `CMakeLists.txt` hochzuladen, jetzt hab ichs gemacht. Eigentlich sollte das jetzt kompilieren, falls nicht, schau ich nochmal, was ich sonst noch so vergessen haben könnte.

**Comment by rickyheinitz** [comment]
Ich hab jetzt weiter gemacht, die Funktionen in extra Dateien zu packen, aber ich verliere gerade den Überblick und frage mich, ob das, was ich da tue, wirklich sinnvoll ist. 
Ich hoffe, ich habe alle wichtigen Dateien hochgeladen und nix vergessen.
Die Ausgabe in die Datei ist momentan unsinnig, die auf der Kommandozeile aber hoffentlich so, wie sie sein soll. Mit der Datei streite ich mich morgen weiter. Da ist das Problem, dass `dump_factored_form` nicht mit der `OStream` Klasse von `nusmv` kommuniziert. Ich hoffe, ich finde morgen eine Lösung dafür.

**Comment by hklarner** [comment]
Puh.
Erste Frage: `try_to_print_this` kann raus aus `mcPrint.c` richtig? Der Code ist ja in `print_states` reinkopiert.

**Comment by rickyheinitz** [comment]
Ja, kann raus. Wollte ich eigentlich noch machen, hatte das dann aber vergessen, sorry.

**Comment by hklarner** [comment]
Kannst Du bitte die Funktion `BddFsm_print_interesting_states_info` nach `mcPrint.c` kopieren und `BddFsmPrint.c` löschen? Es wird gleich klarer, was der Nutzen davon ist.

**Comment by rickyheinitz** [comment]
Hab ich gemacht. Kompiliert zum Glück auch wieder ;)

**Comment by rickyheinitz** [comment]
Hatte noch einen Header in `mcMc.c`, der da nicht mehr sein sollte, rausgenommen. Sollte jetzt gehen.

**Comment by hklarner** [comment]
Fragen bezüglich `print_accepting_states`:
- kann es sein, dass `file_name` und `txt_file_name` mittlerweile identisch sind?
- warum geben wir einmal mit `StreamMgr_print_output`, einmal mit `OStream_printf` und einmal mit `fprint` aus?
- die variable `wffprint` scheint mir eventuell überflüssig, man könnte versuchen 

```
inames[lev] = (const char*) sprint_node(wffprint,
                      BddEnc_get_var_name_from_index(enc, index));
```

durch etwas (in etwa) wie

`inames[lev] = BddEnc_get_var_name_from_index(enc, index));`

zu ersetzen.

Fragen bezüglich `ddAc.c`
- kann es sein, dass wir `dd_dump_factored_form_modified` gar nicht brauchen? Können doch direkt `Cudd_DumpFormula_modified` aufrufen, wozu das kapseln?

Fragen bezüglich `mcPrint.c`
- sind alle includes notwendig?

Bitte nachvollziehen, ob die letzten Änderungen (Commits 116 bis 126) Sinn machen, oder ob ich was wichtiges vergessen / falsch gemacht habe.
Mache morgen weiter. Es fehlen noch
- Implementierung von `print_bdd_size` und einbauen in die Ausgabe

**Comment by rickyheinitz** [comment]
Ich schau mir das auch morgen an und gehe die fragen durch und versuche das ein zu vereinfachen. Der Grund für die unterschiedlichen print Funktionen ist dass wir mal die von nusmv und mal die vom cudd package nutzen. Ich schau morgen mal ob ich das vereinheitlichen kann.

**Comment by rickyheinitz** [comment]
Ich habe versucht, ohne `wffprint` auszukommen, aber das hat zu Speicherzugriffsfehlern geführt. Ich glaube, wir brauchen das weiterhin, weil in `inames[lev] = (const char*) sprint_node(wffprint, BddEnc_get_var_name_from_index(enc, index));` der Variablenname, der von `BddEnc_get_var_name_from_index` zurückkommt, erst noch in einen String umgewandelt werden muss. Wenn ich das richtig verstanden habe gibt `BddEnc_get_var_name_from_index` einen `node_ptr` zurück, und direktes casten zu `char *` funktioniert nicht.

**Comment by rickyheinitz** [comment]
`dd_dump_factored_form` habe ich jetzt rausgenommen, stattdessen wird `Cudd_DumpFormula_modified` direkt aufgerufen. `dd_dump_factored_form` war einfach noch übrig aus dem allerersten Versuch, als es noch direkt in `dd.c` stand. Dereferenzierung vom `DDMgr_ptr` zum `DdManager` passiert jetzt einfach direkt in `Cudd_DumpFormula_modified`, damit ist die Kapselung nicht mehr nötig. Außerdem habe ich mal die Header-Dateien wieder aktualisiert, das hat die Warnungen gleich mal um die Hälfte reduziert.

**Comment by rickyheinitz** [comment]
Ich hab jetzt eine ganz ganz kurze `print_bdd_size` Version, die was ausgibt. Erstmal nur für die Kommandozeilen-Version. Aber wenn das so stimmt, was die zurückgibt, versuche ich, das noch in die Datei zu schreiben.

**Comment by rickyheinitz** [comment]
Ich habe einen Vorschlag für die Vereinheitlichung der Ausgabe-Funktionen. Wird nicht völlig einheitlich dadurch, aber vielleicht ein bisschen besser.
Bei der Kommandozeilen-Ausgabe würde ich es fast so lassen wie es jetzt ist, also den Output mit `StreamMgr_print_output` und `Cudd_DumpFormula_modified`. Wenn wir `print_bdd_size` rausnehmen und stattdessen einfach mit `double size = BddEnc_count_states_of_bdd(enc, states);` in `print_accepting_states` die Größe des jeweiligen bdd berechnen, dann könnten wir die auch einfach mit `StreamMgr_print_output` oder einer anderen `StreamMgr` Funktion ausgeben lassen. Da hätten wir dann also die `nusmv`-eigenen Funktionen, das finde ich eigentlich ganz schön, die zu verwenden.
Aber durch den Wechsel auf `Cudd_DumpFormula_modified` können wir beim Datei-Output nur für die jeweils ersten Zeilen - also die Ausgabe der CTLSPEC - die `StreamMgr` Funktionen verwenden. Wenn man versucht, wieder was mit `OStream_printf`  oder anderen Funktionen schreiben zu lassen, kommt totales Chaos raus. Hab ich ausprobiert, ist nicht gut.
Wir können das auch entweder so lassen, wie es jetzt ist, oder wir gehen einfach ganz zu den C-eigenen Sachen, also zu `fprintf` in Kombination mit `Cudd_DumpFormula_modified`. 
An die CTL-Spec kommt man so als `char*`:

```
node_ptr p = Prop_get_expr(prop);
const char* ctlspec = (const char*) sprint_node(wffprint, p);

```

Was meint ihr, soll ich das ändern, oder so lassen wie's ist?

**Comment by hklarner** [comment]
Hi Frederike,
Du kannst `print_bdd_size` gerne rausnehmen und stattdessen `double size = BddEnc_count_states_of_bdd(enc, states);` in `print_accepting_states` nehmen. Der zweite Punkt ist soweit ich verstanden habe nicht so wichtig. Kannst Du entscheiden.

**Comment by hklarner** [comment]
Würde die Datei [nusmv/core/mc/mcPrint.c](./NuSMV-2.6.0/NuSMV/code/nusmv/core/mc/mcPrint.c) gerne umbenennen, denn _mcPrint_ würde ausgeschrieben heissen _model checking print_, was mir zu generisch ist. Meine Vorschläge:
- `AcceptingStates.c`  (pro: deskriptiv)
- `ac.c`
- `mcAC.c`   (pro: sieht aus wie die anderen Dateinen)
- `printAC.c`

**Comment by rickyheinitz** [comment]
Ich finde umbenennen auch gut, wäre entweder für `AcceptingStates.c` oder für `mcAC.c`

**Comment by hklarner** [comment]
ok, dann nehmen wir `mcAC.c`, dann paßt das Format zu den anderen Dateien.

**Comment by rickyheinitz** [comment]
Ich hab die Dateien entsprechend umbenannt, kompiliert bei mir auch alles noch :)
