### ISSUE TITLE
Abschlußvortrag

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#11]
Dachte wir können schon mal ein paar Punkte für die Vorträge sammeln aus denen ihr dann auswählen könnt.

**Theoretisches**
- kurze Beschreibung model checking: _Übergangsgraph_, _CTL Formel_, _Anfangszustände_ 
- kurze Beschreibung _Decision Diagram_ und _Factored Form_

**Praktisches**
- NuSMV command line option
- CUDD factored form
- Ausgabeformat

**Anwendungen**
- benchmark: "wie lange rechnet NuSMV für ein Boolsches Netz mit `n` Variablen?"
- beispiel: basins of attraction für veröffentlichte Boolsche Netze

Der Vortrag soll zwischen 30 und 60 min lang sein. Ihr könnt euch überlegen, ob ihr einen Vortrag gemeinsam macht (würde ich empfehlen) oder jeder einen eigenen. Als Termin schlage ich
- **10.Mai 14:15**, oder
- **11.Mai 10:15**

vor.

**Comment by rickyheinitz** [comment]
Also, ich kann an beiden Terminen. Und ich fände einen gemeinsamen Vortrag auch besser.

**Comment by hklarner** [comment]
Sarah und Mehmet, ihr auch?

**Comment by ghost** [comment]
Jaa! Das finde ich super:)

**Comment by memocan32** [comment]
Yap klingt sehr gut =)

**Comment by rickyheinitz** [comment]
Sollen wir uns nächste Woche mal treffen, zum Vortrag vorbereiten? Fänd ich gut!

**Comment by hklarner** [comment]
Können wir machen. Irgendeine Terminpreferenz?

**Comment by memocan32** [comment]
Mittwoch gegen 12?

**Comment by rickyheinitz** [comment]
Geht bei mir.

**Comment by ghost** [comment]
jop

**Comment by hklarner** [comment]
Raum 017 ist am Mittwoch zwischen 12:00 und 14:00 für uns reserviert.

**Comment by hklarner** [comment]
Hi, dachte gerade, dass ihr für den theoretischen Teil, als Beispiel an dem ihr Model Checking und BDDs und eine factored formula erklärt, gerne das `raf_network.bnet` nehmen könnt. Also Gleichungen zeigen, Interaktionsgraph und asynchronen Übergangsgraph zeigen. Beispiel spec, beispiel BDD, beispiel formula usw. Was Boolsche Netzwerke und asynchrone Übergänge sind muß nicht erklärt werden.
