### ISSUE TITLE
Interactive Shell

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#12]
Hi, habe gerade von einem der Entwickler bei NuSMV eine Email bekommen:

> > question: would you consider an extension of NuSMV that only
> > adds a command for the batch mode and _does not_ add an extension for
> > the interactive mode?
> 
> We definitely prefer the solution where we will also have the command in
> the interactive shell. Indeed, once ready for the batch doing it for the
> shell should be easy (it would be roughly a matter of wrting the function that
> call the same code it is called in the batch.

Da es anscheinend einfach ist unsere Erweiterung auch im interaktiven Modus ausführbar zu machen, nehme ich das mal mit auf.

**Comment by rickyheinitz** [comment]
Ich kann mir das am Wochenende anschauen. Und auch mal versuchen, rauszukriegen, wie der interaktive Modus funktioniert.

**Comment by ghost** [comment]
Habe die Shell zum Laufen und zur Auswertung gebracht, werde veruchen die command line option auch hier hinzuzufügen.

**Comment by rickyheinitz** [comment]
Yeah! Wie geht das?

**Comment by ghost** [comment]
starten mit 
Pfad/zu/NuSMV -int RET

dann z.B.
read_model -i Pfad/zu/raf_network.smv

flatten_hierarchy

encode_variables

build_model

check_ctlspec -a -o /Pfad/zum/OutputFile -p "TRUE IN raf_network.smv"

--> Testen der CTL True im Rafdings :)

Anleitung :)
http://nusmv.fbk.eu/NuSMV/userman/v21/nusmv_4.html

**Comment by ghost** [comment]
und auf einmal klappt es :D glaube ich... erst hatten sich die Formeln vertseckt und ich sah nur das:
Initial States: 
number of states: 8
Accepting States: 
number of states: 3
Initial and Accepting States: 
number of states: 3
sowohl interaktiv als auch im batch mode mit "print" als filename. Dann durch mir unbekannte schwarze Magie ging auf einmal alles :D

**Comment by rickyheinitz** [comment]
Hab gerade auch nochmal mit `print` getestet, bei mir geht's auch.

**Comment by ghost** [comment]
jo weiß nicht, was da war... schwarze magie :D

**Comment by ghost** [comment]
Die Shell läuft übrigens:) Parameter -a für unsere extension :)
also, zumindestens bei mir...

**Comment by hklarner** [comment]
Cool. Sehe auch, daß es läuft. Folgende Beobachtungen:

##### Auch ohne `-a` werden die initial states usw. angezeigt:

```
NuSMV > check_ctlspec -p "EF(Mek&Raf)"
-- specification EF (Mek & Raf)  is false
-- as demonstrated by the following execution sequence
Trace Description: CTL Counterexample 
Trace Type: Counterexample 
  -> State: 6.1 <-
    Erk = FALSE
    Mek = FALSE
    Raf = FALSE
    STEADYSTATE = FALSE
    SUCCESSORS = 1
    Raf_STEADY = FALSE
    Mek_STEADY = TRUE
    Erk_STEADY = TRUE
    Raf_IMAGE = TRUE
    Mek_IMAGE = FALSE
    Erk_IMAGE = FALSE
Initial States: TRUE
number of states: 8
Accepting States: Erk | (Mek)
number of states: 6
Initial and Accepting States: Erk | (Mek)
number of states: 6
```

EDIT: Ich glaube das liegt daran, daß ich NuSMV mit `-a` gestartet habe. Nicht sicher, ob das so gewünscht ist, woran das liegt.

##### Der Hilfetext läßt `-a` unerwähnt:

```
NuSMV > check_ctlspec -h
usage: check_ctlspec [-h] [-a] [-m | -o file] [-n number | -p "ctl-expr" | -P "name"]
   -h           Prints the command usage.
   -h           Prints the accepting states.
   -m           Pipes output through the program specified
                by the "PAGER" environment variable if defined,
                else through the UNIX command "more".
   -o file      Writes the generated output to "file".
   -n number        Checks only the SPEC with the given index number.
   -p "ctl-expr"    Checks only the given CTL formula.
   -P "name"        Checks only the SPEC with the given name
```

##### Reihenfolge der Parameter relevant?

Zuerst `-a` funktioniert:

```
NuSMV > check_ctlspec -a -p "EF(Mek)"
-- specification EF Mek  is false
-- as demonstrated by the following execution sequence
Trace Description: CTL Counterexample 
Trace Type: Counterexample 
  -> State: 2.1 <-
    Erk = FALSE
    Mek = FALSE
    Raf = FALSE
    STEADYSTATE = FALSE
    SUCCESSORS = 1
    Raf_STEADY = FALSE
    Mek_STEADY = TRUE
    Erk_STEADY = TRUE
    Raf_IMAGE = TRUE
    Mek_IMAGE = FALSE
    Erk_IMAGE = FALSE
Initial States: TRUE
number of states: 8
Accepting States: Erk | (Mek)
number of states: 6
Initial and Accepting States: Erk | (Mek)
number of states: 6
```

Zuerst `-p` funktioniert nicht:

```
NuSMV > check_ctlspec -p "EF(Mek)" -a
usage: check_ctlspec [-h] [-a] [-m | -o file] [-n number | -p "ctl-expr" | -P "name"]
   -h           Prints the command usage.
   -h           Prints the accepting states.
   -m           Pipes output through the program specified
                by the "PAGER" environment variable if defined,
                else through the UNIX command "more".
   -o file      Writes the generated output to "file".
   -n number        Checks only the SPEC with the given index number.
   -p "ctl-expr"    Checks only the given CTL formula.
   -P "name"        Checks only the SPEC with the given name

```

**Comment by ghost** [comment]
oh zum zweiten punkt: da ist nur ein tippfehler drin. das zweite -h sollte eigentlich das -a werden, bei "Prints the accepting states"... da war ich mir nicht ganz sicher, was ich bei der beschreibung reinschreiben sollte...
was soll da am besten rein?
zum dritten punkt teste ich gerade was...

**Comment by ghost** [comment]
So, Punkt 1 lag daran, dass ich die case 'a'- Abfrage mal zum testen an einer anderen Stelle hatte -> korrigiert.
Punkt 2: hatte ohne nachzudenken die if-Abfragen bei den anderen case-Abfragen geklaut.. war doof :D -> entfernt. Nun aber die Frage: Was sollten wir abfragen? Ob -m oder -o Filename sowie ob CTLSPEC übergeben wurde? Scheinen die aber auch nicht zu machen: Testet mal check_ctlspec -o dateipfad. ...
Punkt 3: Warte auf nen Mustertext :) aber immerhin steht nun a da:)

**Comment by ghost** [comment]
PS: Weitere (kreative) Tests beim Aufrufen erwünscht :) Verstecken sich bestimmt noch ein paar Ostereier drin.

**Comment by rickyheinitz** [comment]
Huhu, zu Punkt 3: Vielleicht einfach denselben Text wie im bash-mode? Hier isser: 

``````
-a filename
      prints a factored form formula of the accepting states to the file "filename" 
      or to the command line, if "print" is specified as filename
``` :)
``````

**Comment by ghost** [comment]
jaein. den hatte ich für ne andere stelle gkleut in der mcCMD.c der passt aber nicht ganz wegen filename, ...
angepasst:
 Prints a factored form formula of the accepting states 
      to the file output-file specified with option -o or 
      to the command line, if option -m is selected.

**Comment by ghost** [comment]
hm, wenn man gar keine parameter übergibt, macht es trotzdem -a ... oder?
und schlecht formatiert ist der hilfe text auch noch...
was kann ich eigentlich?

**Comment by ghost** [comment]
man, vorhin hats mit dem ohne -a geklappt, jetzt macht es das wieder immer...

**Comment by hklarner** [comment]
teste gleich auch noch mal..

**Comment by ghost** [comment]
hm, muss ich das vielleicht vorher resetten? merkt es sich das von vorherigen aufrufen?

**Comment by ghost** [comment]
ahh vorher wird eine util_getopt_reset aufgerufen, da muss ich den handler für unsere optiion vermutlich noch einfügen... wird versucht..

**Comment by rickyheinitz** [comment]
Ich hab gerade mal `check_ctlspec -p "EF(Mek&Raf)"` getestet mit einer neu gestarteten shell, da werden die states nicht ausgegeben, nur das gegenbeispiel. Klingt gut mit `util_getopt_reset`!

**Comment by ghost** [comment]
hm, scheint mir so, als würde NuSMV die opts mit "optarg" setzen. Dies wird mit der reset-Funktion resettet. Ist das ok, wenn ich einfach unsere reset_print_accepting() benutze? die scheint zu funktionieren :)

**Comment by rickyheinitz** [comment]
ist doch super, dann hat die auch einen Sinn und hängt da nicht umsonst und einsam rum :)

**Comment by ghost** [comment]
oh nein oh nein bitte nicht testen!!!!

**Comment by ghost** [comment]
ab jetzt darf getestet werden :)

**Comment by hklarner** [comment]
Übrigens `go` ist anscheinend eine Abkürzung für `flatten_hierarchy` usw.:

```
$ ./NuSMV-2.6.0/NuSMV/build/bin/NuSMV -int
NuSMV > read_model -i raf_network.smv
NuSMV > go
NuSMV > check_ctlspec -p "EF(Mek)"
```

#### Tests

##### 1) Option `-m`?

Anscheinend braucht man die Option -m nicht, um das Äquivalent zu `-a print` im batch zu erzielen:

```
NuSMV > check_ctlspec -p "EF(Mek)" -a
-- specification EF Mek  is false
-- as demonstrated by the following execution sequence
Trace Description: CTL Counterexample 
Trace Type: Counterexample 
  -> State: 3.1 <-
    Erk = FALSE
    Mek = FALSE
    Raf = FALSE
    STEADYSTATE = FALSE
    SUCCESSORS = 1
    Raf_STEADY = FALSE
    Mek_STEADY = TRUE
    Erk_STEADY = TRUE
    Raf_IMAGE = TRUE
    Mek_IMAGE = FALSE
    Erk_IMAGE = FALSE

initial states: TRUE
number of initial states: 8
accepting states: Erk | (Mek)
number of accepting states: 6
initial and accepting States: Erk | (Mek)
number of initial and accepting states: 6
```

Selber Output mit `check_ctlspec -p "EF(Mek)" -a -m`.
Ist das beabsichtigt? Finde das ganz gut, können wir gerne so lassen, dann würde ich nur den Hilfetext ändern zu

```
Prints a factored form formula of the initial and accepting states.
```

Das man `-m` und `-o` zusätzlich verwenden kann gilt ja für alle commands. Muss man denke ich nicht extra erwähnen.

##### 2) Starten mit `-a`
- `./NuSMV-2.6.0/NuSMV/build/bin/NuSMV -int -a output.txt` erzeugt wie erwartet keine Datei
- `./NuSMV-2.6.0/NuSMV/build/bin/NuSMV -int -a print` setzt wie erwartet keinen Default für `check_ctlspec`

##### 3) Optionen `-a -o out.txt`

Lenkt die Bildschirmausgabe in `out.txt` um.
- Sehe ich das richtig, daß man aus dem interaktiven Modus heraus nicht dieselbe Ausgabe produzieren kann, wie mit dem Batch Aufruf `NuSMV -a out.txt`?
- Soweit ich sehen kann ist die Erweiterung für den interaktiven Modus fertig, oder? 

EDIT: @rickyheinitz @sarahnee zu Punkt 1) und 3) oben, seht ihr das auch so?
