### ISSUE TITLE
Warnungen durchgehen

### ISSUE THREAD

**Issue by rickyheinitz** [hklarner/SWP2016#14]
Für zum Schluss, wenn alles erstmal steht, denke ich: Beim Kompilieren mit `build/cmake` und `build/make` bekomme ich noch ein paar Warnungen angezeigt. Ich würde die ganz am Ende, wenn alles sonst soweit steht, nochmal durchgehen wollen und schauen, wie wir sie beheben können. 
Nur damit ich's nicht vergesse, jetzt mal als neues Issue aufgenommen.

**Comment by rickyheinitz** [comment]
seit ich die `print_bdd_size()` Funktion rausgenommen hab, gibt es keine Warnungen mehr bei 38% :)
Würd's trotzdem nochmal offen lassen, macht wahrscheinlich so oder so Sinn ganz am Ende nochmal drüber zu gehen, aber mehr so pro forma..

**Comment by ghost** [comment]
Waren bei cmake .. schon immer so viele Warnungen? ganz viel mit Copy_only als unbekannter Parameter oder so, und das Versionsinfo fehlen?

**Comment by hklarner** [comment]
bin mir auch nicht sicher. Eventuell mit `diff` die Ausgaben vergleichen? Hier ist ein Link zum ursprünglichen NuSMV commit:
https://github.com/hklarner/SWP2016/tree/ff5cb851788acaf73e4b1661f323f6efe99561a7

**Comment by ghost** [comment]
mit diff vergleichen mache ich morgen, habe mich heute schon genug von den casestudies ärgern lassen:/

**Comment by rickyheinitz** [comment]
ich hab gerade mal einen der ersten commits getestet ([https://github.com/hklarner/SWP2016/commit/def6254faf5fb830d63734f3241ff9460d4889c4]), das ist der, bei dem wir 'SWP2016' hinzugefügt hatten, beim allerersten waren so viele hartcodierte Pfade in den make-files..) und da habe ich die gleichen Warnungen bei `cmake`. Oberflächliches rumsuchen scheint mir zu sagen, dass das `cmake` spezifische Warnungen sind, die zB die makefiles von Cudd betreffen. `LOCATION, PROJECT_VERSION, COPY` etc. scheinen von cmake gesetzte Variablen zu sein, so weit ich das verstanden hab..
