### ISSUE TITLE
Woche 6

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#15]
Hallo Frederike und Sarah,

habe gerade die aktuelle Version heruntergeladen und getestet. Läuft. Wir haben offiziell noch zwei Wochen und noch ein größeres Thema offen:

 **1)** der interaktive Modus (shell)

und ein paar kleinere

 **2)** Dokumentation
 **3)** Ausgabe wie in [output_corrected.txt](../../SWP2016/blob/master/output_corrected.txt)
 **4)** [Warnungen durchgehen](../../SWP2016/issues/14)

und ein optionales

 **4)** benchmark

überlegt euch wer wann an welchem Thema arbeitet. Ich bin von jetzt bis zum Schluß da und helfe mit wo ich kann.

**Comment by ghost** [comment]
Ich glaube, das mit der Shell habe ich doch schon gemacht? Oder 
funktioniert das nicht? Habe ich das Richtige hochgeladen?

**Comment by hklarner** [comment]
Im Prinzip schon. Es gibt aber noch ein paar Fragen und `check_ctlspec -h` sollte auch `-a` erwähnen. Siehe  Issue [Interactive Shell](../../SWP2016/issues/12).

**Comment by rickyheinitz** [comment]
**zu 2)** Ich kann mich jetzt nochmal mit `doxygen` streiten, und wenn ich das dann immer noch nicht verstehe, würde ich einfach morgen versuchen, aus dem Rest der Doku schlau zu werden und Vorschläge für Kommentare schreiben.
**zu 4)** Wie ist das denn mit den Benchmark-Files gedacht? Alle `.smv`-files im Casestudies-Ordner durchlaufen lassen und messen, wie lange `nusmv` braucht? Ich fänd das auf jeden Fall gut, das noch zu machen.

**Comment by hklarner** [comment]
ich habe mich mit doxygen noch nicht auseinandergesetzt. Es gibt die html version ja online:

http://nusmv.fbk.eu/NuSMV/progman/v26/html/

so was wäre ganz gut. Außerdem erinnere ich mich irgendwo Anweisungen zum Dokumentieren gesehen zu haben, kann ich aber gerade nicht mehr finden. Komme noch mal darauf zurück.

Falls Du mit doxygen schon html oder pdf Seiten generiert hast, schreib mal kurz wie Du das gemacht hast.

**Comment by hklarner** [comment]
.. das Thema Benchmark bekommt ein eigenes Issue. Fände ich auch gut, wenn ihr das noch schafft. Macht sich auch gut als Folie im Vortrag.

**Comment by rickyheinitz** [comment]
Ich hab gerade ein pdf file erzeugt. im ordner `NuSMV-2.6.0/NuSMV/doc/prog-man/rules/` einfach `make latexpdf` laufen lassen. Allerdings wird dann einfach nur das pdf, das eh schon da ist (`rules.pdf`) nochmal mit allen latex-files im Ordner `build/latex` erzeugt. na super. anyway, ich würde mich einfach an dem pdf-file orientieren und schau mal, wie weit ich damit komme.

**Comment by sarahnee** [comment]
oh nein bitte nicht testen!!

**Comment by hklarner** [comment]
hm. Das sind ja nur die Rules. Frage mich, wie die tatsächliche Dokumentation erzeugt wird.

**Comment by rickyheinitz** [comment]
Das ist mir auch ein Rätsel. Ich hab nochmal versucht, den Anleitungen in der Readme zu folgen: 

```
For generating the documentation, run from top-level directory
(trunk/NuSMV2/NuSMV) the following:
doxygen doc/doxygen/doxygen_nusmv.conf
```

Dann werden auch irgendwelche html-files generiert, aber nicht da, wo die Readme es behauptet, und auch nicht so, dass es was anderes als eine leere Seite mit nusmv-Header zutage fördern würde. Das ist mir alles etwas unklar.
