### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#16]
Die Idee ist mit einer Stoppuhr festzuhalten, wie lange NuSMV typischerweise braucht um die Accepting states zu berechnen. Die Erwartung und Vermutung ist, daß die Ausgabe der Accepting States keine nennenswerte CPU Zeit brauch, da das entsprechende BDD ja sowiso berechnet werden muss.

Wie lange NuSMV rechnet hängt erstens von der größe des Netzwerks ab und zweitens von der oder den CTL Formeln. 
##### Welche Netzwerke testet man?

 1) Zufällig generierte Netzwerke mit einem Parameter **n**, der festlegt wieviele Komponenten es gibt (bei `raf_network.bnet` sind es drei), siehe [Benchmark](../../SWP2016/blob/master/Benchmark)
 2) Publizierte Netzwerke, siehe [Casestudies](../../SWP2016/blob/master/Casestudies)
##### Welche CTL Formeln testet man?

Die einfachste Möglichkeit ist Formeln des Typs `EF(x)` zu testen, wobei `x` einen einzelnen Zustand referenziert, für `x=110` wäre die Formel also

`EF(Erk & Mek & !Raf)`

Dabei kann man `x` auch wieder zufällig generieren.

Für die case studies macht es Sinn eine CTL Formel für einen Attraktor zu generieren. Die Formeln kann ich generieren.
##### Wie stoppt man die Zeit?

Vielleicht mit dem Linux Befehl `time`? Siehe http://linux.about.com/library/cmd/blcmdl1_time.htm
Ausgabe sieht zum Beispiel so aus:

```
$ time NuSMV -r big_network.smv
...
...
system diameter: 1
reachable states: 5.49756e+11 (2^39) out of 5.49756e+11 (2^39)

real    9m13.250s
user    9m6.884s
sys 0m6.256s
```
##### Wie präsentiert man die Ergebnisse?
- man könnte die Größe des Netzwerkes, also **n**, gegen die CPU Zeit **t** plotten.
- für die case studies könnte man eine Tabelle mit den Zeiten angeben
- für zufällige Ergebnisse könnte man angeben wie lange (wieviele Zeichen) die accepting states Formel ist
- die Zeit kann man einmal mit `-a` und einmal ohne `-a` stoppen und vergleichen

**Comment by rickyheinitz** [comment]
ich hab mal die Netzwerke im Casestudies Ordner laufen lassen und die Datei mit den gemessenen Zeiten hochgeladen. Noch nicht hübsch, aber erstmal da. Das `mapk` Ding braucht allerdings ewig - soll das so sein?

**Comment by rickyheinitz** [comment]
ach so, gemessen hab ich mit `time`, angegeben ist die Systemzeit mit und ohne `-a`

**Comment by hklarner** [comment]
jup, `mapk.smv` braucht ewig.

**Comment by ghost** [comment]
hab nochmal für die casestudies (außer mapk) mittelwerte aus je 20 durchläufen gebildet. leider hat das shellskript mich ordentlich verarscht... habe tausend for-schleifen versucht, aber irgendwie klappte es nicht so wie ich wollte, also jetzt ganz unelegant je 20 mal copy+paste vom funktionsaufruf... r-skript zur mittelwertsberechnung sowie ergebnisse sollten auch da sein... manno...

**Comment by hklarner** [comment]
juhu, verstehe nicht ganz, weshalb Du bei den casestudies Wiederholungen machst. Die laufen ja jeweils immer in derselben Zeit. Oder meinst Du die Zufallsnetzwerke (benchmark)? Da tauchen für jedes n ja bei jedem Aufrauf von `step1.r` andere Netzwerke auf, die manchmal schwerer manchmal leichter zu checken sind.

Du kannst auch scripte hochladen, die nicht tun was Du möchtest (for-schleifen) vielleicht fällt jemand anderem etwas ein.

Bei den casestudies wäre es interessant die Basins of Attraction genauer zu verstehen. `boolean_cell_cycle.smv` hat zum Beispiel zwei Attraktoren (deshalb die zwei CTL specs). Jede spec kodiert "man kann den jeweiligen Attraktor erreichen". Und zu jeder spec bekommen wir die factored form und die Anzahl der Zustände. Wie kann diese Information dargestellt werden? Ein Basin kann zB von 1000 Zuständen erreichbar sein, der andere nur von 10. Außerdem (das steht zur Zeit noch nicht in der Datei) kann man noch fragen welche Zustände _beide_ Attraktoren erreichen können und welche _jeweils nur einen_. In welcher Form kann man diese ganzen Informationen am Besten darstellen? (weiß nicht genau. Venn-Diagramm? ein gerichteter Graph?)

EDIT: gerade gesehen, dass du ein script hochgeladen hast
EDIT2: das die Zeiten für dasselbe Netzwerk (dieselbe `smv` Datei) immer gleich sind gleich sieht man auch in der `timeout.txt`

**Comment by ghost** [comment]
Habe nun ewig versucht mit R die Venndiagramme zu machen... mit den packages, die ich bisher versucht habe: absoluter Mist. Tortendiagramme gehen allerdings... 
werde morgen mal versuchen für python oder so schöne venn-packages zu finden. 
Zu den CTLs:
hätte man beispielsweise 3 original ctls, habe ich nach dem schema
A, B, C
0, 0, 0    --> !A & !B & !C
0, 0, 1    --> !A & !B & C
0, 1, 0    --> !A & B & !C
0, 1, 1    --> !A & B & C
und so weiter..
die Teilmengen erstellt. Ist das Richtig?? War zwischendurch sehr, sehr verwirrt...

**Comment by hklarner** [comment]
Hi Sarah. Ja, super, so meinte ich das. Wenn es drei Attraktoren X,Y,Z gibt, also drei CTL Erreichbarkeitsformeln A=EF(X), B=EF(Y) und C=EF(Z), dann ergeben sich deine 8 Kombinationen.

Das Problem bei **Venn-Diagrammen** ist, dass man die nicht für beliebig viele Mengen darstellen kann, siehe [hier](https://en.wikipedia.org/wiki/Venn_diagram#Extensions_to_higher_numbers_of_sets), sondern eigentlich nur für 2,3 und 4 Mengen.
Der wiki Artikel erwähnt übrigens explizit den Zusammenhang mit einer Wahrheitstabelle, wie Du sie oben stehen hast, siehe das Bild [hier](https://en.wikipedia.org/wiki/Venn_diagram#Related_concepts).
Ich würde sagen, dass so eine Tabelle als Ausgabe im Textformat schon genug ist. Dabei können alle Zeilen, für die die entsprechende CTL Formel _falsch_ ist, weggelassen werden.

Ich habe ja letztes mal an der Tafel versucht einen Graphen darzustellen und war selbst verwirrt, was die Kanten bedeuten sollen. Ich meinte sogenannte **Hasse-Diagramme**, das sind Graphen, deren Knoten so ähnlich aussehen wie deine Zeilen oben, also 000, 001, 010, usw. aber die 0 hat eine andere Bedeutung, nämlich dass die entsprechende CTL Formel _nicht_ in der Konjunktion auftaucht:

```
A, B, C
0, 0, 0 --> True
0, 0, 1 --> C
0, 1, 0 --> B
0, 1, 1 --> B & C
```

und so weiter. Dadurch ergibt sich die Kantenrelation "ist Teilmenge von", wie in den Bildern [hier](https://en.wikipedia.org/wiki/Hasse_diagram), allerdings anscheinend nur für Knoten, die sich durch _genau eine 1 unterscheiden_. Es gibt also eine Kante 111 --> 011 aber keine Kante 111 --> 001, was in unserem Fall unpraktisch ist, falls es z.B. nur die Knoten 111 und 001 gibt (denn dann hätte man trotzdem gerne die Kante 111 --> 001).

Graphen kann man gut im _dot_ Format darstellen, das sind Textdateien, aus denen man mit dem Programm `dot` ein Bild des Graphen generieren kann. Einfaches Beispiel `hasse.dot`:

```
digraph mygraph{
      "{}" -> "{A}" 
      "{}" -> "{B}" 
      "{}" -> "{C}" 
      "{A}" -> "{A,B}" 
      "{A}" -> "{A,C}" 
      "{B}" -> "{A,B}" 
      "{B}" -> "{B,C}"
      "{C}" -> "{A,C}"
      "{C}" -> "{B,C}"
      "{A,B}" -> "{A,B,C}" 
      "{A,C}" -> "{A,B,C}" 
      "{B,C}" -> "{A,B,C}" 
}
```

Kompiliert wird das z.B. per `dot -Tpdf hasse.dot -o hasse.pdf`, was folgendes Bild erzeugt:
[hasse.pdf](https://github.com/hklarner/SWP2016/files/248325/hasse.pdf).

**Comment by rickyheinitz** [comment]
ich hab jetzt noch ein rscript erstellt, das die komplexität der antwortformeln (also accepted und initaccepted) gegen n plottet. bin aber gerade verwirrt, ob das so gedacht war oder ob das jetzt quatsch war.

**Comment by hklarner** [comment]
Hi Frederike. Ja, war soweit ich sehen kann genau so gedacht. Der Grund, warum die beiden Linien übereinander liegen ist, dass die initial states immer durch `INIT TRUE` definiert sind. Dadurch ist die Anzahl der Zeichen von init und initaccepting immer genau gleich. Für dieses setup kannst du also auch nur die Komplexität von accepting plotten.

**Comment by ghost** [comment]
Hab jetzt erstmal den Quatsch hochgeladen, den ich mit R zustande gebracht habe... Versuche nun noch etwas anständiges mit Python hinzuzaubern...

**Comment by ghost** [comment]
oh ähhmm, accepting oder initaccepting? :D
EDIT: Ich vermute mal letzteres? Sonst geht das mit den Sizes auch nicht ganz auf...

**Comment by hklarner** [comment]
Hi Sarah, kannst Du mir an einem Beispiel oder mit einer `readme.md` erklären, wie die scripte verwendet werden?

**Comment by rickyheinitz** [comment]
ich hab jetzt noch eine dritte grafik gemacht, in der die anzahl der accepting states geplottet wird (`number_of_states.r`). Dann ist das Benchmarking fertig, oder?

**Comment by rickyheinitz** [comment]
also, der teil mit den zufallsnetzwerken, meinte ich..

**Comment by ghost** [comment]
Habe nun etwas besseres für die Casestudies hochgeladen. Allerdings weiß ich nicht, ob die Ausgaben korrekt sind. Noch auf der Suche nach Tests.
Lässt sich ausführen mit:
sh basins_in_subsets.sh networkname.smv
erstellt dann networkname.dot, networkname.txt, networkname.pdf 
und noch viele mehr :D 
allerdings fehler noch beim Pfad zu NuSMV, ich hatte es ursprünglich in einem anderen Ordner, korrigiere ich gleich mal
Das mit R hatte ich nur hochgeladen, damit man sieht, dass ich was mache.. ist aber eher Müll...

**Comment by ghost** [comment]
ah mit, jetzt habe ich die ganzen files mit hochgeladen :D aber Pfad zu nusmv sollte stimmen
EDIT: oder doch nicht (die Files...)

**Comment by ghost** [comment]
hm, bei boolean_cell_cycle.smv ist keine von den subset_ctls wahr... ist das so oder ist das ein fehler bei meinen permutationen? mal abgesehen davon, dass ich das bei der ausgabe nicht abgefangen habe....
EDIT: ah gut, die ist mit den eingaben false. sorry fürs zuspammen

**Comment by hklarner** [comment]
habe eben mal

```
./basins_in_subsets.sh boolean_cell_cycle.smv
```

ausgeführt (übrigens, `./basins_in_subsets.sh ../boolean_cell_cycle.smv` funktioniert nicht). Es entstehen dann 6 Dateien. `boolean_cell_cycle.txt` ist die `nusmv -a` Ausgabe von `boolean_cell_cycle_prepared.smv` und soweit ich sehe hast Du die Formeln richtig konstruiert.

In `boolean_cell_cycle.txt` gibt es 2 Kombinationen die mehr als 0 accepting states haben, nämlich (0,1) und (1,0). Wahrscheinlich suchst Du nach den Kombinationen, die "ANSWER: TRUE" enthalten? Ich meinte die Kombinationen, die mehr als 0 accepting states haben :)

**Comment by ghost** [comment]
ah okay:) hatte ich falsch verstanden, korrigiere ich nachher mal :)

**Comment by ghost** [comment]
so, ein paar Korrekturen vorgenommen. Nimmt nun die accepting states/sizes und schreibt die Größe an die Knoten. Probleme sind noch, dass die Pfeile durch die Größenbeschriftungen gehen und es sehr platt gequetscht aussieht beim fissionYeastDavidich2008.smv.
Ist es ansonsten denn halbwegs richtig?

**Comment by ghost** [comment]
Ich schaffe es leider nicht, die Graphen richtig zu proprtionieren... Besonders beim fissionYeastDavidich... hmm

**Comment by hklarner** [comment]
Hi Sarah, ist alles richtig. Das der Graph plattgequetscht aussieht und die Pfeile durch die Beschriftungen gehen ist kein Problem - Graphlayouts machen nie das, was man will.

Ich verstehe die Pfeile noch nicht ganz. Z.B. gibt es einen von 

> (0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0) -> (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

oder mal einen Schritt zurück: erzeugst Du das **Venn** oder **Hasse** Diagramm?
- Die Factored Formeln der accepting states wären noch interessant
- Du kannst beim Aufrufen von NuSMV `-dcx` übergeben, um die Zeit für die Berechnung der Gegenbeispiele zu sparen
- Hast Du schon probiert die Knoten relativ zur _Size_ zu skalieren? Kann man soweit ich mich erinnere mit `[shape=circle, fixedsize=true, width=2]`

**Comment by ghost** [comment]
ist weder hasse noch venn, weil die genauso wenig sinn machen, wie dass, was ich momentan mache. die mengen sind doch alle paarweise disjunkt oder nicht? oder ich müsste, bei der erstellung der teilmengen doch verodern, dann würde eine art von hasse, in der aber leere mengen weggelassen werden, sinn machen. also zb. 0011 als 0 & 0 & (1 | 1)? da hatte ich mich ja am anfang schon gewundert.... 
accepting formel baue ich noch mit in den txt output. soll ich da dann sie CTL weglassen? ist ja eh total unübersichtlich und die teilmengen beschreibung zb 0010 ist ja da...
das mit dem relativen skalieren probiere ich nachher mal aus...

**Comment by hklarner** [comment]
Ob die Mengen disjunkt sind hängt davon ab, von welchen Mengen Du sprichst. 0011 bedeutet bei Venn !A&!B&C&D und damit repräsentieren die Kombinationen disjunkte Mengen von Zuständen.

Bei Hasse bedeutet 0011 nur C&D und damit können sich die Mengen überschneiden, zum Beispiel ist 0111 eine Teilmenge von 0011. Siehe dazu den Post oben.

Verodern würde ich glaube ich nicht, dann weiß man ja nicht mehr genau welchen Attraktor die Menge erreichen kann.

Verstehe noch nicht nach welcher Regel Du Kanten zwischen Knoten ziehst.

**Comment by ghost** [comment]
hab versucht immer eine verbindung zum nächst größeren zu machen, da ich immer noch keine ahnung habe wie es aussehen soll. alle knoten mit size 0 habe ich weggelassen. aber ist wie üblich eh sinn- und zwecklos

**Comment by hklarner** [comment]
hi, als ich würde noch die beiden Definitionen von Knoten (0011 als Hasse oder Venn) ausprobieren. Im Venn Fall ist eine Tabelle eigentlich sogar genug, glaube ich. Im Hasse Fall machen Kanten ja sind: es gibt eine Kante von x nach y wenn sich x und y in einem Bit unterscheiden und x<y gilt.
