### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#17]
Die Dokumentation sollte drei Teile enthalten:
- _Sourcecode_ habt ihr ja schon angefangen
- _Changelog_, kurz aufzählen welche Dateien und Funktionen geändert / erzeugt wurden
- _Manual_ das an einem Beispiel (`raf_network.smv`?) alle typischen batch und interaktiv Modus Aufrufe kurz (inklusive Ausgabe) zeigt und erklärt

Würde vorschlagen ihr erzeugt dazu "markdown" Dateien im Repository: `changelog.md` und `manual.md`

**Comment by rickyheinitz** [comment]
Ich glaube, ich bin jetzt mit allen _source_files durch, hab gerade noch die Vorschläge für `ddAc.c` und `ddAc.h` hochgeladen.

**Comment by rickyheinitz** [comment]
ach nee, zu früh gefreut, die Dateien für den interaktiven Modus fehlen noch.

**Comment by rickyheinitz** [comment]
Ich bin heute auf der Arbeit, deshalb kann ich leider nicht weiter machen mit der Dokumentation. Aber mein Plan ist, dass ich morgen Vorschläge für `Changelog` und `Manual` erstelle. Und dann würde ich am Samstag mit den Benchmark-Tests anfangen.

**Comment by rickyheinitz** [comment]
Ich hab jetzt auch die Änderungen für die Shell kommentiert, hoffe, das ist ok so und ich hab nichts vergessen.

**Comment by rickyheinitz** [comment]
Ich hab Vorschläge für `changelog.md` und `manual.md` hochgeladen. Hab bei der `changelog` noch versucht, jeweils kurz zu beschreiben, was wir in welcher Datei geändert haben.
Geht das ungefähr in die Richtung, die du dir vorgestellt hattest? Sonst kann ich das auch gerne wieder ändern.

**Comment by hklarner** [comment]
hab ich mir so vorgestellt, ja.  Beim manual kann die Variante mit `-dcx` im Batch und auch mit `-m` für die Shell wieder raus, denke ich, da die ja nicht unsere Funktion betreffen (dcx) bzw nicht nötig sind (m), richtig?
Außerdem wäre es gut noch kurz (paar Sätze) zu beschreiben, was ausgegeben wird, d.h. was eine factored form forumla ist (hier zum Beispiel: [011-factored-forms.ppt](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&sqi=2&ved=0ahUKEwjcxaPehaLMAhUBkCwKHbsdDusQFghJMAE&url=http%3A%2F%2Fusers.ece.utexas.edu%2F~adnan%2Fsyn-07%2F011-factored-forms.ppt&usg=AFQjCNHO9FpH3cikRHjlXNjaO1_nF_n3cw&bvm=bv.119745492,d.bGg)) und was "initial", "accepting" und "inital and accepting" sind.

**Comment by rickyheinitz** [comment]
Ah ja, stimmt, dann nehm ich das wieder raus und ergänze die Beschreibungen noch.

**Comment by rickyheinitz** [comment]
uiuiui, ich hab versucht, die beschreibungen zu ergänzen, aber ich bin mir nicht sicher, ob dabei nicht vielleicht völliger blödsinn rausgekommen ist..

**Comment by hklarner** [comment]
top
