### ISSUE TITLE
add NuSMV command line option "-a output.txt" and "-a"

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#2]
"-a" for "return accepting states"

without filename "-a"
- prints accepting states only

with file filename "-a output.txt"
- prints accepting states and saves accepting states in "output.txt"

**Comment by rickyheinitz** [comment]
Ich hab's geschafft, eine simple Flag zu setzen: `-a` kann jetzt uebergeben werden (im Bash-Mode, den interaktiven hab ich mir nicht angeschaut..)
Dafuer hab ich in `opt.h` die Option `RETURN_ACCEPTING` definiert und die Funktionen deklariert, mit denen die Option gesetzt werden kann (Zeilen 410; 1271ff.),
in `opt.c` werden die Funktionen definiert, wichtig ist glaube ich erstmal v.a. `boolean opt_return_accepting(OptsHandler_ptr opt)`, mit der abgefragt werden kann, ob die Flag gesetzt wurde oder nicht. 
Die Flag muss dann noch in `optPkg.c` registriert werden (Zeilen 203ff.)
Ist jetzt erstmal nur die `-a` Flag, und ich weiss auch nicht, ob das im interaktiven Modus auch funktioniert, oder ob wir dafuer noch `Cmd_CommandAdd(env, "check_ctlspec", CommandCheckCtlSpec, 0, true)` anschauen muessen. Wahrscheinlich schon.
Und die Ergaenzung mit `-a output.txt` hab ich auch noch nicht hinbekommen, schade..
Aber mal ein Start.

**Comment by rickyheinitz** [comment]
Ich habe weiter mit den CommandLineOptions gespielt. Es scheint mir aber nicht moeglich zu sein, dass das zusaetzliche Argument optional ist, sondern es muss immer gesetzt werden. Deshalb habe ich zum Anfang mal eine neue CommandLineOption hinzugefuegt, `-a_file`. Wenn die aufgerufen wird, werden die Ergebnisse in die Datei `interesting_states.txt` und `interesting_states.dot` geschrieben, aber nicht auf der Kommandozeile ausgegeben. Dafuer koennen beide Optionen gemeinsam verwendet werden, wenn man beides haben will. Auf jeden Fall muessten wir uns diese Punkte nochmal naeher anschauen, denke ich:
- wie kann Dateiname als zusaetzliche Option uebergeben werden?
- Alternative: `specs` aus `env` abgreifen, in `char*` umwandeln und als Dateinamen verwenden
- Ausgabe des Files laeuft im Moment noch mit `dd_dump_factored_form`, sollte aber auf `BddFsm_print_interesting_states_info` geaendert werden wegen der besseren Lesbarkeit. Aber ich habe noch nicht verstanden, wie ich den `StreamMgr` von nusmv ueberreden kann, in eine Datei zu schreiben.

**Comment by hklarner** [comment]
Um **benötigte** zusätzliche Parameter zu übergeben kann man sich an der Flag `-v vl` orientieren, d.h. dem docstring der Funktion `NuSMVCore_add_env_command_line_option` in der Datei [cinit.h](../blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/cinit/cinit.h). Siehe Punkt 3:

> 3) parameter -> NULL if none, a string value if any

Nach kleiner Recherche denke ich, dass **optionale** zusätzliche Parameter in NuSMV eventuell gar nicht vorgesehen sind (macht das Parsen der Flags ja auch sehr schwierig). Zwei unterschiedliche Flags `-a` und `-a_file` sind also in Ordnung.

Ich versuche auch mal herauszubekommen wie die Namen der CTL Formeln oder die Formeln selbst aus `env` zu bekommen sind. Die bräuchten wir ja um mehrere Ergebnisse in einer Datei zu speichern.
