### ISSUE TITLE
Funktion schreiben, die Mc_CheckCTLSpec erweitert

### ISSUE THREAD

**Issue by rickyheinitz** [hklarner/SWP2016#3]
- void Mc_CheckCTLSpec_printResults(NuSMVEnv_ptr env, Prop_ptr prop)
- soll bestehende Mc_CheckCTLSpec erweitern und statt dieser aufgerufen werden, wenn nusmv -a aufgerufen wird
- rausfinden, wo Mc_CheckCTLSpec aufgerufen wird, um dort abzufragen, welche Variante ausgefuehrt werden soll

**Comment by rickyheinitz** [comment]
So, ich hab jetzt einfach mal mit dem einfachsten angefangen und die Mc_CheckCTLSpec so veraendert, dass die Ausgabe jetzt in der Funktion selber passiert. 
Die Original-Version der Funktion steht in der Datei noch drin, aber fuers Testen hab ich sie erstmal auskommentiert. Muss dann wieder rein, wenn die Flags funktionieren und die veraenderte Funktion muss dann umbenannt werden.

**Comment by rickyheinitz** [comment]
Vielleicht ist das Quatsch, aber vielleicht auch nicht: die Mc_CheckCTLSpec()- Funktion wird in Prop.c aufgerufen (/code/nusmv/core/prop/Prop.c) und vielleicht müssen wir da dann die switch/case-Abfrage erweitern, wenn die Flags definiert sind. In der Funktion void prop_verify (ab Zeile 1489).

**Comment by hklarner** [comment]
doch, das sieht gut aus. Frage mich immer noch, wie wir `Mc_CheckCTLSpec()` erweitern sollten. 

(1) Funktion kopieren und eine größtenteils identische Variante von `Mc_CheckCTLSpec()` definieren, die zum Beispiel `Mc_CheckCTLSpec_accepting()` heißt.

(2) Herausfinden, wie aus `env` die Parameteroption `-a` herausgelesen werden kann. Dann kann man zum Schluß von `Mc_CheckCTLSpec()` abfragen ob `-a` übergeben wurde und dann gegebenenfalls die accepting states speichern oder printen.

Ich tendiere jetzt doch zu Variante (2). Das meiner Meinung stärkste Argument dafür ist, daß zukünftige Änderungen an der model checking Prozedur dadurch nicht die Funktionalität unserer Erweiterung einschränken. Außerdem ist identischer Code in zwei Funktionen doof. Was denkst Du?

Ich schaue mir gerade an, wie die Option `-v vl` (set verbose level) funktioniert und denke `env` enthält alle Informationen, die wir brauchen..

**Comment by rickyheinitz** [comment]
So beim nochmal drüber nachdenken scheint mir auch die zweite Variante sinnvoller zu sein. Dann müssen wir wahrscheinlich auch an weniger Dateien ran, die Prop.c müssten wir dann zum Beispiel gar nicht verändern. Frage mich nur, ob wir dann das printen wieder in eine extra Funktion packen sollten (wegen der Übersichtlichkeit) oder das einfach so wie's jetzt ist in der `Mc_CheckCTLSpec()` lassen sollten.

Ich werde mal versuchen, ob ich an die Informationen in `env` rankomme, das wäre sowohl für die Kommandozeilenparameter gut als auch für die Variablen aus der smv-Datei, denke ich.

**Comment by hklarner** [comment]
In der Funktion `Mc_CheckCTLSpec` in [core/mc/mcMc.c](../blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/mc/mcMc.c) wird am Anfang der "Optionshandler" aus `env` erzeugt:

`const OptsHandler_ptr opts OPTS_HANDLER(NuSMVEnv_get_value(env, ENV_OPTS_HANDLER));` (Zeile 99)

und später damit abgefragt was der "verbosity level" ist:

`if (opt_verbose_level_gt(opts, 0)) { ... }` (Zeile 107)

So könnte das auch für den Parameter `-a` funktionieren, sobald der richtig registriert ist.

**Comment by rickyheinitz** [comment]
so, nochmal zum Thema an die Variablen rankommen. ich hänge da gerade fest und komme nicht weiter.
Was ich probiert habe: 
Variablen ausgeben lassen mit `BddEnc_print_vars_in_cube`. Das gibt, je nachdem, was ich der Funktion uebergebe, entweder einen Speicherzugriffsfehler oder einen internal error. Das nervt. Ich würde gerne wissen, ob die Ausgabe eventuell nützlich sein könnte.
Auch probiert habe ich `BddEnc_print_set_of_inputs`, endete auch mit Speicherzugriffsfehler, d.h. da muss ich beim Aufruf irgendwas falsch gemacht haben, aber weiß nicht was.
`BddEnc_print_set_of_state_input_pairs` hat funktioniert, ich könnte mal versuchen, eine Funktion zu schreiben, die die Variablennamen da rausholt und in ein Array speichert.

**Comment by rickyheinitz** [comment]
Neue Idee: Ich hab jetzt die `BddFsm_print_reachable_states_info` Funktion getestet aus der Datei `BddFsmPrint.c`. Die gibt huebsche Formeln aus, so was zum Beispiel: `FORMULA = (Mek & (Erk | Raf))`
Die vorhandenen Funktionen sind nicht das, was wir brauchen, glaube ich (reachable states, fair states, ...) aber vielleicht lassen sie sich ja anpassen fuer initial states, accepting states und initial accepting states.
