### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#4]
In der Datei [NuSMV-2.6.0/NuSMV/code/nusmv/core/opt/opt.c](../blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/opt/opt.c) in der Zeile

`void unset_return_acceptin(OptsHandler_ptr opt)`

ist ein Typo ("acceptin" anstatt von "accepting")

**Comment by rickyheinitz** [comment]
hab ich korrigiert. und noch einen anderen fehler auch, hatte an einer stelle vergessen, `return_accepting` in `print_accepting` zu aendern.
