### ISSUE TITLE
Ausgabeformate

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#5]
Der Befehl **-a** soll folgende Zeilen ausgeben (keine Leerzeilen vorher oder nacher):

> Initial States: (Erk & !Mek)
> Accepting States: Erk
> Initial and Accepting States: (Erk & !Mek)

und zwar _nach_ den anderen print statements, die in `Mc_CheckCTLSpec` [core/mc/mcMc.c](../../SWP2016/blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/prop/mcMc.c) sonst noch stehen (zum Beispiel das counterexample). Die Idee ist, daß die Ausgabe so aussieht, wie die anderen NuSMV Ausgaben. Da die ursprüngliche Formel schon angegeben ist, müssen wir die nicht nochmal ausgeben.

Der Befehl **-a_file** soll _eine einzige Datei_ erzeugen in der füŕ jede CTL specification ein Block mit vier Zeilen steht. Blöcke sind durch einzelne Leerzeilen getrennt. Folgendes Beispiel ist für zwei CTL specifications:

> CTLSPEC________AG(Erk)
> INIT_____________(Erk & !Mek)
> ACCEPTING______Erk
> INITACCEPTING__(Erk & !Mek)
> 
> CTLSPEC________EF(Erk)
> INIT_____________(Erk & !Mek)
> ACCEPTING______Erk
> INITACCEPTING___FALSE

wobei die underscores "`__`" durch Leerzeichen ersetzt werden sollen. Die Idee hier ist, daß die Datei leicht weiterverarbeitet werden kann, jede Zeile ist im Grunde ein keyword, value Paar, und die Leerzeichen sollen dafür sorgen, dass die Datei trotzdem gut lesbar ist. Der string, der hinter CTLSPEC stehen soll steckt irgendwo in `Prop_print` (glaube ich) in [core/mc/mcMc.c](../../SWP2016/blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/prop/mcMc.c). Eventuell funktioniert auch `Prop_get_expr` aus [core/prop/Prop.c](../../SWP2016/blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/prop/Prop.c).

Der **Name der Datei**, die durch **-a_file** erzeugt wird soll durch den user angegeben werden, durch einen _benötigten parameter_. Wie das geht wird in dem docstring von `NuSMVCore_add_command_line_option` in [core/cinit/cinit.h](../blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/cinit/cinit.h) erwähnt. Orientieren kann man sich an der command line option `-v vl` bei der `vl` der benötigte paramter ist.

Ansonsten super, was ihr alles geschafft habt! Habe die aktuelle Version eben kompiliert und ausprobiert. Läuft.

**Comment by rickyheinitz** [comment]
ich hab gerade festgestellt, dass es in den commandline options für die Flag `-a` schon gibt. Deshalb hab ich unsere in `-ac` und `-ac_file` geändert. Nur sicherheitshalber.
Ausserdem hab ich schonmal ein bisschen in den `opt.c` und `opt.h` Dateien aufgeraeumt.
Ich schau mir auch nochmal an, wie `nusmv` die Fehler abfängt, wenn kein Dateiname übergeben wird und was genau sie mit den `default`-Werten machen und versuche, das dann noch anzupassen in der `-a_file` Option.

**Comment by hklarner** [comment]
Ändern in `-ac` ist ok. Aber komisch, in `nusmv -h` stand `-a` ja nicht drin. Wo hast du `-a` gefunden?

**Comment by rickyheinitz** [comment]
ich glaub das war ein denkfehler von mir. ich hatte das bei den interaktiven commandline-options entdeckt, dachte ich jedenfalls. jetzt hab ich nochmal geschaut und festgestellt, dass es bei einigen befehlen die option `-a` gibt, wenn der interaktive modus genutzt wird. aber da werden scheinbar optionen pro befehl definiert, deshalb war das quatsch, dass ich das geändert hab. ich würde es einfach wieder rückgängig machen, wenn ich die optionen zusammenführe. sorry, war verwirrt.

**Comment by hklarner** [comment]
alles gut :)

**Comment by hklarner** [comment]
Ich habe gerade die aktuelle Version mit der Datei [raf_network.smv](../../SWP2016/blob/master/raf_network.smv) getestet - läuft - und bekomme folgende Textdatei [output.txt](../../SWP2016/blob/master/output.txt). Das ist fast richtig. Die richtige Ausgabe ist in [output_corrected.txt](../../SWP2016/blob/master/output_corrected.txt) zu sehen. Die Änderungen betreffen folgende Punkte:

(1) Es soll für jede spec ein Block mit vier Zeilen erzeugt werden und die Blöcke sollen durch eine einzelne Leerzeile getrennt sein.
(2) Die `case ... esac;` Darstellung soll durch die entsprechende Formel ersetzt werden.

Kann jemand bitte kurz hierauf antworten, damit ich weiß, wer das issue übernimmt?

**Comment by rickyheinitz** [comment]
ich kann mir das anschauen. die leerzeichen hatten mich auch schon genervt, bisher hatte ich keine idee, wie die rauszukriegen sind, aber ich versuchs nochmal.

**Comment by hklarner** [comment]
Hi!
Ich habe mir die Ausgabe von `BddFsm_print_reachable_states_info` mal genauer angeschaut. Wir haben die Funktion für `BddFsm_print_interesting_states_info` ja kopiert. Die Stelle, an der die Formel generiert wird, verwendet `BddEnc_print_bdd_wff`, d.h. das BDD wird in WFF umgewandelt, wobei WFF anscheinend für "_well formated formula_" steht. Leider gehört das `case ... esac;` Konstrukt zur Definition einer solchen Formel. Das heißt es wird gar nicht so einfach aus einem BDD einen reinen Boolschen Ausdruck zu generieren. Möglichkeiten, die mir einfallen
- (1) Wir haben Glück und es gibt irgendwo noch eine passenedere Funktion, die das macht was wir wollen
- (2) Wir schreiben eine eigene Funktion, die prüft, ob `case ... esac;` in der Formel auftaucht und erzeugen gegebenenfalls daraus einen richtigen Boolschen Ausdruck

EDIT: der erste Fall scheint eingetreten zu sein.

**Comment by hklarner** [comment]
Hier noch eine Erweiterung: In `BddFsm_print_reachable_states_info` werden zusätzlich zu einer Formel auch die Kardinalität der Mengen ausgegeben:

```
OStream_printf(file, "reachable states: %g (2^%g) out of %g (2^%g)\n",
          reached_cardinality, log(reached_cardinality)/log(2.0),
          search_space_cardinality, log(search_space_cardinality)/log(2.0));
```

Das wollen wir auch für alle drei Sets!

**Comment by sarahnee** [comment]
Füge ich wieder mit ein.

**Comment by ghost** [comment]
Ist wieder mit drin. Absolut unübersichtlich. Fehlerabfrage muss man sich noch überlegen, wie das geht.

**Comment by hklarner** [comment]
Hi Sarah,
ich habe [output_corrected.txt](../../SWP2016/blob/master/output_corrected.txt) aktualisiert. In Klammern wird die Anzahl der repräsentierten Zustände angegeben. In der letzten Zeile jedes Blocks wird mit `ANSWER: TRUE` oder `ANSWER: FALSE` einfach angegeben, ob die spec erfüllt ist. Denke man kann mit

`if (Prop_get_status(self->prop) == Prop_True) { ... }`

entscheiden, ob `TRUE`  oder `FALSE` ausgegeben werden soll. Die search space cardinality brauchen wir nicht (weil offensichtlich) und die Umrechnung in exponentielle Schreibweise brauchen wir glaube ich auch nicht. Wäre eventuell für die Ausgabe auf den Bildschirm interessant, aber in der Datei soll die exakte Anzahl stehen.

EDIT: die Zahlen in Klammern machen die Ausgabe in zwei Spalten etwas komplizierter, weil die Anzahl der Leerzeichen von der Länge der Zahl abhängen.

**Comment by rickyheinitz** [comment]
Nochmal zu den Ausgabeformaten mit `dump_factored_form`: Ich hab das `f0 =` jetzt erstmal drin gelassen, das wird gesetzt, wenn statt `char ** onames` `NULL` übergeben wird. Wenn man output names übergibt, dann werden die statt `f0` genommen, d.h. wir könnten `dump_factored_form` einfach unsere State Bezeichnungen übergeben. Ich war nur leider zu blöd, die `onames` richtig zu setzen, hab ständig irgendwelche Fehler mit dem Speicher allocieren und freigeben gemacht. Ich schau mir das aber nochmal genauer an, das sollte ja eigentlich ganz einfach gehen.

**Comment by sarahnee** [comment]
klappt bei euch die Ausgabe mit "print" als filename?

**Comment by hklarner** [comment]
`-a print` erzeugt gerade folgende Ausgabe:

```
Initial States: TRUE
number of states: 8
Accepting States: Erk | (Mek)
number of states: 6
Initial and Accepting States: Erk | (Mek)
number of states: 6
```

folgende hätte ich gerne (orientiert sich an der Ausgabe von `-r`)

```
initial states: TRUE
number of initial states: 8
accepting states: Erk | (Mek)
number of accepting states: 6
initial and accepting states: Erk | (Mek)
number of initial and accepting States: 6
```

**Comment by rickyheinitz** [comment]
Ich bin gerade eh an der Ausgabe dran, ich ändere das noch entsprechend. Ich hab mich jetzt für die `fprintf` Variante beim in die Datei schreiben entschieden, ich glaube, dann brauchen wir insgesamt ein paar Variablen weniger. Dachte, das ist dann vielleicht übersichtlicher.

**Comment by rickyheinitz** [comment]
Ich hab jetzt die neue Version hochgeladen. Ich hoffe, das stimmt jetzt alles so und ich hab mich nicht irgendwo geirrt.

**Comment by sarahnee** [comment]
gerade als ich auch pushen wollte :D
