### ISSUE TITLE
cuddGarbageCollect

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#6]
Keine Ahnung, ob das ein echter bug ist oder nur vorübergehend. Jedenfalls führt

`NuSMV -a -dcx big_network.smv`

zu folgendem Fehler:

> cuddGarbageCollect:
> problem in table 1
>  dead count != deleted
>  This problem is often due to a missing call to Cudd_Ref
>  or to an extra call to Cudd_RecursiveDeref.
>  See the CUDD Programmer's Guide for additional details.Aborted (core dumped)

**Comment by rickyheinitz** [comment]
hab das auch gerade getestet, das passiert sowohl bei der `-a print` als auch bei der `-a file` variante, wir müssen also nochmal suchen, wo das passieren kann. sollte nicht an der `dump_dot`-Funktion liegen, zumindest hatte ich die gerade auskommentiert und das ergebnis war dasselbe. leider.

**Comment by rickyheinitz** [comment]
Also, ich hab gerade nochmal geschaut. Nur mit den `initial states` läuft es problemlos durch. Aber weder mit den `accepting states` noch mit den `init_and_accepting states` klappt es. Mein Verdacht ist gerade, dass wir noch irgendwo ein `bdd_free` vergessen haben und es an den `bdd_and_accumulate` Aufrufen in `mcMc.c` liegt, weil dort auf `dd.c` und damit die Cudd-Bibliotheken zugegriffen wird. Ich teste das jetzt mal.

**Comment by rickyheinitz** [comment]
Also, ich hab gerade nochmal geschaut. Nur mit den `initial states` läuft es problemlos durch. Aber weder mit den `accepting states` noch mit den `init_and_accepting states` klappt es. Mein Verdacht ist gerade, dass wir noch irgendwo ein `bdd_free` vergessen haben und es an den `bdd_and_accumulate` Aufrufen in `mcMc.c` liegt, weil dort auf `dd.c` und damit die Cudd-Bibliotheken zugegriffen wird. Ich teste das jetzt mal.

**Comment by rickyheinitz** [comment]
ich kam bei der Fehlersuche nicht weiter. Das hat mich frustriert. Deshalb hab ich jetzt nochmal eine alternative Variante reingenommen: output mit `dd_dump_factored_form` (wie ganz am Anfang), aber ich hab die Input Names mit drin diesmal. Dann wird auch der `case ... esac` Kram nicht mit ausgegeben, aber insgesamt find ich die Formel nicht so schoen und das `f0 =` sollte wahrscheinlich auch noch raus. Ich bin mir gerade nicht sicher, welcher weg jetzt sinnvoller ist, nach dem Fehler in der `print_states` Funktion zu suchen oder die `dd_dump` Variante.. 
Das, was ich jetzt gerade hochgeladen hab, läuft mit dem großen Netzwerk noch nicht, weil ich den Aufruf der `print_states` Funktion noch dringelassen hab, um die Ausgabe der Formeln in beiden Varianten vergleichen zu können.

**Comment by hklarner** [comment]
Hi, ich schaue mir das ab 15:00 genauer an. Das dann auch nicht der `case ... esac` Kram ausgegeben wird hört sich interessant an. Melde mich sobald ich was herausgefunden habe.

**Comment by hklarner** [comment]
Hi, die Version mit `dd_dump_factored_form` scheint mir sinnvoller. Die löst soweit ich sehen kann auch das `case` problem. Basiert deine `try_to_print_this` auf einer existierenden Funktion?

Wegen des Ausgabeformats: was hältst Du davon einfach die ersten fünf Zeichen `f0 =` zu löschen und alle `+` durch `|` und alle `*` durch `&` zu ersetzen?

**Comment by hklarner** [comment]
ich glaube wir sollten uns tests überlegen, um sicher zu gehen, dass die Formeln richtig sind. Gib mal 

```
INIT TRUE
CTLSPEC TRUE
```

in `raf_network.smv` ein. Die Ergebnisse stimmen nicht, NuSMV liefert:

```
-- specification TRUE  is true
Initial states: FALSE
Accepting states: TRUE
Initial accepting states: FALSE

Test DumpFactoredForm Initial States: f0 = CONST0
Test DumpFactoredForm Accepting States: f0 = CONST1
Test DumpFactoredForm Accepting States: f0 = CONST0
```

richtig wäre:

```
-- specification TRUE  is true
Initial states: TRUE
Accepting states: TRUE
Initial accepting states: TRUE

Test DumpFactoredForm Initial States: f0 = CONST1
Test DumpFactoredForm Accepting States: f0 = CONST1
Test DumpFactoredForm Accepting States: f0 = CONST1
```

Ich suche auch mal nach der Ursache. Übrigens: die Konstanten `CONST1` und `CONST0` sollten auch noch durch `TRUE` und `FALSE` ersetzt werden.

**Comment by hklarner** [comment]
Ich vermute, dass wir `init` nicht korrekt berechnen. In den Zeilen 143 wird `s0` durch `s0 & tmp2` ersetzt, richtig? Und wir kopieren dieses `s0` dann als unser init. Ich weiß nicht genau, was `tmp2` repräsentiert. Ich versuche mal herauszufinden, was die state constraints in `BddFsm_get_state_constraints` bedeuten..

**Comment by ghost** [comment]
hm.. mit meiner (vielleicht veralteten) version gibt es das richtige aus...

**Comment by ghost** [comment]
mit der frisch gepullten version gibt es bei mir anscheinend auch das richtige aus. Auf jeden Fall für Init und Ctlspec = True. Da ist alles True.

**Comment by hklarner** [comment]
finde das mal raus! falls du keine changes hast, geh einfach auf Frederickes letzten commit zurück (bevor meinem vermeindlichen bugfix):

`git checkout 14bd4e6ba302b974db3d0da100da658d774d3c0c`

der hash steht bei den jeweiligen commits dabei. Du solltest `Initial states: (Erk | Mek)` bekommen, obwohl in `raf_network.smv` steht `INIT TRUE`.

Mit `git checkout master` kommst du zurück zur aktuellen Version.

**Comment by rickyheinitz** [comment]
Ich hab gerade auch das big network mit der aktuellen version getestet. Das ist bei mir ohne Fehlermeldung durchgelaufen. 
Wegen der `dd_dump_factored_form` denke ich, dass es schwierig sein dürfte, die Ausgabe zu verändern, weil die im wesentlichen auf eine Funktion aus dem `Cudd` Package zurückgreift. Und ich hab keine Ahnung, wie/ob wir da die Ausgabe in einen `char *` umwandeln können, um den verändern zu können. Falls der Fehler mit der letzten Version jetzt behoben ist, erscheint es mir fast einfacher, zu versuchen, den `case ... esac` Kram rauszukriegen, oder zumindest ähnlich aufwendig.
Beim Test mit 
`INIT TRUE
CTLSPEC TRUE`
gibt die letzte Version bei mir die Ausgabe
`-- specification TRUE  is true
Initial states: TRUE
Accepting states: TRUE
Initial accepting states: TRUE

Test DumpFactoredForm Initial States: f0 = CONST1
Test DumpFactoredForm Accepting States: f0 = CONST1
Test DumpFactoredForm Initial and Accepting States: f0 = CONST1`

**Comment by hklarner** [comment]
> hm.. mit meiner (vielleicht veralteten) version gibt es das richtige aus...

@sarahnee hast Du rausgefunden, ob das bei dir wirklich schon vorher geklappt hat? Würde mich stark wundern...

**Comment by ghost** [comment]
Bei der oben genannten Version kam tatsächlich Quatsch raus. Lag an den Init-States :) Werden aber nun ja sowieso erst später separat abgerufen.
