### ISSUE TITLE
Fehlermeldung: Input file is (null)

### ISSUE THREAD

**Issue by hklarner** [hklarner/SWP2016#7]
Hi noch mal,

ich tendiere gerade dazu die beiden command line options **-a** und **-a_file** zu einer einzigen, nämlich **-a**, zusammenzufassen. Und zwar so:
- **-a** kann **entweder** eine Datei erzeugen **oder** die Ergebnisse als Text ausgeben
- **-a** benötigt einen parameter _filename_
- ein bestimmter Wert von _filename_ ist, sozusagen als "cheat", für die Bildschirmausgabe reserviert:
  - falls man `filename=print` angibt wird der Text ausgegeben und keine Datei erzeugt
  - andernfalls wird kein Text ausgegeben aber dafür in eine Datei geschrieben

Ich glaube dadurch ist die Verwendung einfacher, weil der User weniger Auswahlmöglichkeiten hat. Was denkt ihr? Gibt's dadurch irgendwelche Nachteile?

**Comment by rickyheinitz** [comment]
Ah, jetzt erst gesehen, hatte gerade noch mit der -a_file-Option gespielt. Ich finde das klingt gut. vielleicht könnten wir auch print als default-wert setzen? ich könnte das machen.

**Comment by hklarner** [comment]
ok, dann lass uns das ausprobieren. Ich weiß allerdings nicht was "default-wert" genau heißt, denn so wie ich die command line options mit parameter verstehe, muss man trotzdem einen parameter angeben. D.h. in welchem Fall würde denn der default greifen?

**Comment by rickyheinitz** [comment]
ich hab die commandline options jetzt so geändert, dass es nur noch die option `-a` gibt. man kann zwar `print` als default-Wert setzen, aber dann wird immer die Option ausgeführt, deshalb hab ich das jetzt wieder rausgenommen. Wenn `print` als filename angegeben wird, wird auf die Kommandozeile geschrieben, sonst in die angegebene Datei.

**Comment by hklarner** [comment]
gerade getestet, läuft. Default rausnehmen ist gut. Eine Sache noch: Der falsche Aufruf `-a raf_network.smv` gibt den Fehler

`Input file is (null). You must set the input file before.`

aus. Besser wäre ein Hinweis darauf welche Option, nämlich `-a`, den Dateinamen erwartet. Habe gerade in [core/cinit/cinitBatch.c](../../SWP2016/blob/master/NuSMV-2.6.0/NuSMV/code/nusmv/core/cinit/cinitBatch.c) nachgeschaut, ob man das schnell ändern kann. Bin nicht sicher, ob daß überhaupt die richtige Datei ist. Falls Du weißt, wie das geht, wäre

`filename for option -a is (null). You must set the filename.`

eine schönere Fehlermeldung - **Aber**: falls das nicht einfach zu machen ist, dann so lassen.

**Comment by rickyheinitz** [comment]
hab ich in `cinitBatch.c` geändert (einfach eine zusätzliche if-Abfrage hinzugefügt)
